name: Django Deployment to EC2

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  deploy:
    name: Deploy Django to EC2
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify your Python version

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run tests (Optional)
    # - name: Run tests
    #   run: |
    #     python manage.py test

    # Deploy to EC2
    - name: Deploy to EC2
      env:
        EC2_USER: ubuntu                     # Change to your EC2 username (e.g., ec2-user, ubuntu)
        EC2_HOST: ${{ secrets.EC2_HOST }}    # Public IP/Domain of your EC2 instance, stored as a GitHub secret
        EC2_KEY: ${{ secrets.EC2_SSH_KEY }}  # SSH private key, stored as a GitHub secret
      run: |
        # Add the private key for SSH
        echo "${EC2_KEY}" > ssh_key
        chmod 600 ssh_key

        # Connect to EC2 and deploy
        ssh -o StrictHostKeyChecking=no -i ssh_key $EC2_USER@$EC2_HOST << 'EOF'
          # Navigate to the project directory
          cd /path/to/your/project

          # Pull latest changes from the repository
          git pull origin main

          # Activate virtual environment
          source venv/bin/activate

          # Install dependencies
          pip install -r requirements.txt

          # Run database migrations
          python manage.py migrate

          # Collect static files
          python manage.py collectstatic --noinput

          # Restart the server (Gunicorn/uwsgi and Nginx)
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
        EOF
