name: Django Deployment to EC2

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  deploy:
    name: Deploy Django to EC2
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Specify your Python version

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run tests (Optional)
    # - name: Run tests
    #   run: |
    #     python manage.py test

    # Deploy to EC2
    - name: Deploy to EC2
      env:
        EC2_USER: ubuntu                     # Change to your EC2 username (e.g., ec2-user, ubuntu)
        EC2_HOST: ${{ secrets.HOST_DNS }}    # Public IP/Domain of your EC2 instance, stored as a GitHub secret
        EC2_KEY: ${{ secrets.EC2_SSH_KEY }}  # SSH private key, stored as a GitHub secret
      run: |
        # Add the private key for SSH
        mkdir -p ~/.ssh  # Create the .ssh directory if it doesn't exist
        echo "$EC2_KEY" > ~/.ssh/ssh_key
        chmod 600 ~/.ssh/ssh_key

        # Connect to EC2 and deploy
        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
        ssh -T -i ~/.ssh/ssh_key $EC2_USER@$EC2_HOST << EOF
        echo "Connected successfully"
        cd /home/
        git pull origin main
        source venv/bin/activate
        pip install -r requirements.txt
        python manage.py migrate
        python manage.py collectstatic --noinput
        sudo systemctl restart gunicorn
        sudo systemctl restart nginx
        EOF
